"""Add club_id && Comment

Revision ID: 05ba0c83bf08
Revises: 
Create Date: 2026-01-26 15:34:51.800846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ba0c83bf08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('club_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'meetings', 'clubes', ['club_id'], ['id'])
    op.add_column('testing', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testing', 'comment')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'club_id')
    op.create_table('test_users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
