"""Age2

Revision ID: c22c9f2ca0eb
Revises: ca81fb42df9d
Create Date: 2026-02-17 14:06:17.945424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22c9f2ca0eb'
down_revision: Union[str, Sequence[str], None] = 'ca81fb42df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age2')
    # ### end Alembic commands ###
